#!/bin/zsh

if [ -d /usr/local/opt/make/libexec/gnubin ]; then
	PATH=/usr/local/opt/make/libexec/gnubin:$PATH
fi
if [ -d /usr/local/opt/coreutils/libexec/gnubin ]; then
	PATH=/usr/local/opt/coreutils/libexec/gnubin:$PATH
fi

if [[ -z "$INSIDE_EMACS" ]]; then
	test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
fi

eval `dircolors -b "${HOME}/.dircolors"`

eval $(thefuck --alias)


