#!/bin/zsh


if [[ -z "$INSIDE_EMACS" ]]; then
	test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
fi

eval `dircolors -b "${HOME}/.dircolors"`

eval $(thefuck --alias)


